### ISSUE TITLE
Can a project also be launched without a token?

### ISSUE THREAD

**Issue by TimDaub** [jbx-protocol/juice-contracts-v2#21]
Hi,

I found your project to be quite interesting and I'd conaider raising funds with my project rugpullindex.com. But we aren't setup to launch our own token. Is it possible to create a juicebox without launching a token?

**Comment by kungmink** [comment]
คุณสนใจแบบไหน

**Comment by TimDaub** [comment]
:/

**Comment by mejango** [comment]
yes can be launched without a token!
